-- MySQL Script generated by MySQL Workbench
-- Tue 06 Mar 2018 11:46:43 AM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema minichat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema minichat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `minichat` DEFAULT CHARACTER SET utf8 ;
USE `minichat` ;

-- -----------------------------------------------------
-- Table `minichat`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minichat`.`user` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minichat`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minichat`.`message` (
  `ID` INT NOT NULL,
  `message` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `user_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `user_ID`),
  INDEX `fk_message_user_idx` (`user_ID` ASC),
  CONSTRAINT `fk_message_user`
    FOREIGN KEY (`user_ID`)
    REFERENCES `minichat`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
